### ISSUE TITLE
Supplementary Data question

### ISSUE THREAD

**Issue by RichardScottOZ** [e-farahbakhsh/Gawler_MPM#2]
Hi all - I notice shapefiles used here - will the paper detail what you did with those? e.g. not in repostitory, presumably for size or other reasons.

**Comment by e-farahbakhsh** [comment]
Hi Richard - The database (vector and raster datasets) we used is over 20 GB and will be available as soon as the paper is published.

**Comment by RichardScottOZ** [comment]
Thanks. Yeah, I can pretty much take a good guess at replicating.  A note of interest for other people though.

Given the usual slowness of such things - any idea on realistic timeframe?

**Comment by e-farahbakhsh** [comment]
I really can't give an accurate timeframe...maybe mid of next year!

**Comment by RichardScottOZ** [comment]
Yes, accurate within the bounds of that lot.

Good enough.
